export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';
export const SET_CHAT_REQUEST = 'SET_CHAT_REQUEST';
export const CLEAN_STORE = 'CLEAN_STORE';
export const SET_CHAT_DATA_PROVIDER = 'SET_CHAT_DATA_PROVIDER';